services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  app:
    build:
      context: .
      dockerfile: Dockerfile   # Make sure your file is named exactly this
    container_name: express_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://admin:qwerty@mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data:



# After running docker compose up -d, where does your app run?
# Your app (app service) runs inside a Docker container, not directly on your host machine.
# You can access it from your host at http://localhost:3000 because of the published port mapping ("3000:3000").
# All dependencies and code run isolated in the container environment.
# You do not need to run your app separately on your host machine.